FROM python:3.12

# Set the working directory inside the container
WORKDIR /app

# Copy the application files to the working directory
COPY . .

# Set the command to run your application
CMD ["python", "app.py"]
